blank_issues_enabled: true
contact_links:
  - name: BetterTouchTool Forum Topic
    url: https://community.folivora.ai/t/useless-notch-dynamic-notch-meet-hi-notch/35649/
    about: Please ask and answer questions here.