name: Feature request
description: Suggest an idea for Hi Notch!
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: Accepted are answers in `English`, `Polish`.
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when [...]
  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the feature request here.
  - type: checkboxes
    attributes:
      label: ' '
      options:
        - label: >-
            I verified that the suggestion has not already been requested on GitHub.
          required: true
        - label: I verified that the suggestion has not already been requested on BTT Forum.
          required: true